{{- if and .Values.collaboration.onlyoffice.enabled (and .Values.collaboration.onlyoffice.persistence.enabled (not .Values.collaboration.onlyoffice.persistence.existingClaim)) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "opencloud.fullname" . }}-onlyoffice-data
  annotations:
    "helm.sh/resource-policy": "keep"
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: onlyoffice
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.collaboration.onlyoffice.persistence.size | default "2Gi" }}
  {{- with include "opencloud.storageClass" (dict "local" .Values.collaboration.onlyoffice.persistence.storageClass "global" .Values.global.storage.storageClass) }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
