{{- if and (not .Values.collaboration.onlyoffice.config.coAuthoring.secret.existingSecret) .Values.collaboration.onlyoffice.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencloud.fullname" . }}-onlyoffice
type: Opaque
stringData:
  sessionSecret: {{ .Values.collaboration.onlyoffice.config.coAuthoring.secret.session.string }}
{{- end }}
---
{{- if and (not .Values.collaboration.onlyoffice.config.rabbitmq.existingSecret) .Values.collaboration.onlyoffice.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencloud.fullname" . }}-rabbitmq
type: Opaque
stringData:
  url: {{ .Values.collaboration.onlyoffice.config.rabbitmq.url }}
{{- end }}