{{- if and .Values.identityProvider.internal.ingress.enabled .Values.identityProvider.internal.enabled }}
{{- $ingressClassName := .Values.identityProvider.internal.ingress.ingressClassName | default .Values.global.ingress.ingressClassName }}
{{- $annotationsPreset := .Values.identityProvider.internal.ingress.annotationsPreset | default .Values.global.ingress.annotationsPreset }}
{{- $annotations := merge (deepCopy .Values.identityProvider.internal.ingress.annotations) (deepCopy .Values.global.ingress.annotations) }}
{{- $tlsEnabled := .Values.identityProvider.internal.ingress.tls.enabled | default .Values.global.ingress.tls.enabled }}
{{- $tlsSecretName := .Values.identityProvider.internal.ingress.tls.secretName | default .Values.global.ingress.tls.secretName }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "opencloud.fullname" . }}-keycloak
  annotations:
    {{- if $annotationsPreset }}
    {{- include (printf "opencloud.ingress.annotations.%s" $annotationsPreset) . | nindent 4 }}
    {{- end }}
    {{- with $annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if $ingressClassName }}
  ingressClassName: {{ $ingressClassName | quote }}
  {{- end }}
  {{- if $tlsEnabled }}
  tls:
    - hosts:
        - {{ .Values.global.domain.keycloak | quote }}
      {{- if $tlsSecretName }}
      secretName: {{ $tlsSecretName }}
      {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.global.domain.keycloak | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "opencloud.fullname" . }}-keycloak
                port:
                  number: 8080
{{- end }}
