{{- if and .Values.opencloud.enabled (and .Values.opencloud.persistence.config.enabled (not .Values.opencloud.persistence.config.existingClaim)) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "opencloud.opencloud.fullname" . }}-config
  annotations:
    "helm.sh/resource-policy": "keep"
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: opencloud
spec:
  accessModes:
    - {{ .Values.opencloud.persistence.config.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.opencloud.persistence.config.size | quote }}
  {{- with include "opencloud.storageClass" (dict "local" .Values.opencloud.persistence.config.storageClass "global" .Values.global.storage.storageClass) }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}

{{- if and .Values.opencloud.enabled (and .Values.opencloud.persistence.data.enabled (not .Values.opencloud.persistence.data.existingClaim)) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "opencloud.opencloud.fullname" . }}-data
  annotations:
    "helm.sh/resource-policy": "keep"
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: opencloud
spec:
  accessModes:
    - {{ .Values.opencloud.persistence.data.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.opencloud.persistence.data.size | quote }}
  {{- with include "opencloud.storageClass" (dict "local" .Values.opencloud.persistence.data.storageClass "global" .Values.global.storage.storageClass) }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}

{{- if and (eq .Values.opencloud.storage.mode "posixfs") (and .Values.opencloud.storage.posixfs.persistence.enabled (not .Values.opencloud.storage.posixfs.persistence.existingClaim)) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "opencloud.opencloud.fullname" . }}-posixfs
  annotations:
    "helm.sh/resource-policy": "keep"
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: opencloud
spec:
  accessModes:
    - {{ .Values.opencloud.storage.posixfs.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.opencloud.storage.posixfs.persistence.size | quote }}
  {{- with include "opencloud.storageClass" (dict "local" .Values.opencloud.storage.posixfs.persistence.storageClass "global" .Values.global.storage.storageClass) }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
