{{- if .Values.opencloud.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opencloud.opencloud.fullname" . }}
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: opencloud
spec:
  type: ClusterIP
  ports:
    - port: 9200
      targetPort: http
      protocol: TCP
      name: http
    {{- if not .Values.opencloud.nats.external.enabled }}
    - port: 9233
      targetPort: 9233
      protocol: TCP
      name: nats
    {{- end }}
    {{- $collaboraEnabled := .Values.collaboration.collabora.enabled }}
    {{- $onlyofficeEnabled := .Values.collaboration.onlyoffice.enabled }}
    {{- if or $collaboraEnabled $onlyofficeEnabled }}
    - port: 9300
      targetPort: 9300
      protocol: TCP
      name: collaboration-http
    - port: 9301
      targetPort: 9301
      protocol: TCP
      name: collaboration-grpc
    {{- end }}
  selector:
    {{- include "opencloud.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: opencloud
{{- end }}
