{{- if .Values.opencloud.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opencloud.serviceAccountName" . }}
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
  {{- with .Values.opencloud.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
